CREATE TABLE STUDENT (ID INTEGER NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), univId INTEGER, PRIMARY KEY (ID))
CREATE TABLE UNIVERSITY (UNIVID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY (UNIVID))
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_univId FOREIGN KEY (univId) REFERENCES UNIVERSITY (UNIVID)
